licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "live_calculators",
    deps = [
        "//mediapipe/calculators/core:flow_limiter_calculator",
        "//mediapipe/graphs/custom/face_mesh:facemesh_deps",
    ],
)
